#!/usr/bin/env bash
# How fix Ubuntu container's to listen on port 80
new="80 default_server"
old="8080 default_server"
sed -i "s/$old/$new/" /etc/nginx/sites-enabled/default
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
