#!/usr/bin/env bash
# This script is displaying Time
h=0
min=0  
while [ $h -ne 12 ]
do
	if [ $min = 0 ]; then
		((min++))
		echo "Hour: $h"
		echo "$min"
	elif [ $min = 59 ]; then
		echo "$min"
		min=0
		((h++))
	else 
		echo "$min"
		((min++))
	fi
	
done
